#RF Pmod JE
set_property PACKAGE_PIN W16 [get_ports spi_rtl_io0_io]
set_property PACKAGE_PIN J15 [get_ports spi_rtl_io1_io]
set_property PACKAGE_PIN H15 [get_ports spi_rtl_sck_io]
set_property PACKAGE_PIN V12 [get_ports {spi_rtl_ss_io[0]}]
set_property PACKAGE_PIN V13 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property PACKAGE_PIN U17 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property PACKAGE_PIN T17 [get_ports {gpio_rtl_0_tri_io[2]}]
#OLED Pmod JD
set_property PACKAGE_PIN T15 [get_ports spi_rtl_0_io0_io]
set_property PACKAGE_PIN P14 [get_ports spi_rtl_0_io1_io]
set_property PACKAGE_PIN R14 [get_ports spi_rtl_0_sck_io]
set_property PACKAGE_PIN T14 [get_ports {spi_rtl_0_ss_io[0]}]
set_property PACKAGE_PIN U14 [get_ports {gpio_rtl_tri_io[0]}]
set_property PACKAGE_PIN U15 [get_ports {gpio_rtl_tri_io[1]}]
set_property PACKAGE_PIN V17 [get_ports {gpio_rtl_tri_io[2]}]
set_property PACKAGE_PIN V18 [get_ports {gpio_rtl_tri_io[3]}]

set_property IOSTANDARD LVCMOS25 [get_ports {spi_rtl_*}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_rtl_tri_io[*]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_rtl_0_tri_io[*]}]
set_property PULLDOWN true [get_ports {spi_rtl_*}]
set_property PULLDOWN true [get_ports {gpio_rtl_tri_io[*]}]
set_property PULLDOWN true [get_ports {gpio_rtl_0_tri_io[*]}]