# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.cache/wt [current_project]
set_property parent.project_path F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/design_hw.bd
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_processing_system7_0_0/design_hw_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_0_0/design_hw_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_0_0/design_hw_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_0_0/design_hw_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_rst_processing_system7_0_100M_0/design_hw_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_rst_processing_system7_0_100M_0/design_hw_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_rst_processing_system7_0_100M_0/design_hw_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_xbar_0/design_hw_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_1_0/design_hw_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_1_0/design_hw_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_1_0/design_hw_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_2_2/design_hw_axi_gpio_2_2_board.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_2_2/design_hw_axi_gpio_2_2_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_axi_gpio_2_2/design_hw_axi_gpio_2_2.xdc]
set_property used_in_implementation false [get_files -all f:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/ip/design_hw_auto_pc_0/design_hw_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/design_hw_ooc.xdc]
set_property is_locked true [get_files F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/design_hw.bd]

read_vhdl -library xil_defaultlib F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/sources_1/bd/design_hw/hdl/design_hw_wrapper.vhd
read_xdc F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/constrs_1/new/my_constraints.xdc
set_property used_in_implementation false [get_files F:/Proiecte_si_concursuri/WWS/WWS/ZYBO/zybo_vivado_proj/zybo_vivado_proj.srcs/constrs_1/new/my_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_hw_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef design_hw_wrapper.dcp
catch { report_utilization -file design_hw_wrapper_utilization_synth.rpt -pb design_hw_wrapper_utilization_synth.pb }
