# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/my_constraints.xdc

# Block Designs: bd/design_hw/design_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw || ORIG_REF_NAME==design_hw}]

# IP: bd/design_hw/ip/design_hw_processing_system7_0_0/design_hw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_processing_system7_0_0 || ORIG_REF_NAME==design_hw_processing_system7_0_0}]

# IP: bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_0_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_0_0}]

# IP: bd/design_hw/ip/design_hw_axi_gpio_0_0/design_hw_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_0_0 || ORIG_REF_NAME==design_hw_axi_gpio_0_0}]

# IP: bd/design_hw/ip/design_hw_processing_system7_0_axi_periph_0/design_hw_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_hw_processing_system7_0_axi_periph_0}]

# IP: bd/design_hw/ip/design_hw_rst_processing_system7_0_100M_0/design_hw_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_hw_rst_processing_system7_0_100M_0}]

# IP: bd/design_hw/ip/design_hw_xbar_0/design_hw_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_xbar_0 || ORIG_REF_NAME==design_hw_xbar_0}]

# IP: bd/design_hw/ip/design_hw_xlconcat_0_0/design_hw_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_xlconcat_0_0 || ORIG_REF_NAME==design_hw_xlconcat_0_0}]

# IP: bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_1_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_1_0}]

# IP: bd/design_hw/ip/design_hw_axi_gpio_1_0/design_hw_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_1_0 || ORIG_REF_NAME==design_hw_axi_gpio_1_0}]

# IP: bd/design_hw/ip/design_hw_axi_gpio_2_2/design_hw_axi_gpio_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_2_2 || ORIG_REF_NAME==design_hw_axi_gpio_2_2}]

# IP: bd/design_hw/ip/design_hw_axi_gpio_3_0/design_hw_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_3_0 || ORIG_REF_NAME==design_hw_axi_gpio_3_0}]

# IP: bd/design_hw/ip/design_hw_auto_pc_0/design_hw_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_auto_pc_0 || ORIG_REF_NAME==design_hw_auto_pc_0}]

# XDC: bd/design_hw/ip/design_hw_processing_system7_0_0/design_hw_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_processing_system7_0_0 || ORIG_REF_NAME==design_hw_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_0_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_0_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_0_0/design_hw_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_0_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_0_0/design_hw_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_0_0 || ORIG_REF_NAME==design_hw_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_0_0/design_hw_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_axi_gpio_0_0/design_hw_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_0_0 || ORIG_REF_NAME==design_hw_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_rst_processing_system7_0_100M_0/design_hw_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_hw_rst_processing_system7_0_100M_0}]

# XDC: bd/design_hw/ip/design_hw_rst_processing_system7_0_100M_0/design_hw_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_hw_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_hw_rst_processing_system7_0_100M_0}]

# XDC: bd/design_hw/ip/design_hw_rst_processing_system7_0_100M_0/design_hw_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_xbar_0/design_hw_xbar_0_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_1_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_1_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_axi_quad_spi_1_0/design_hw_axi_quad_spi_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_quad_spi_1_0 || ORIG_REF_NAME==design_hw_axi_quad_spi_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_1_0/design_hw_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_1_0 || ORIG_REF_NAME==design_hw_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_1_0/design_hw_axi_gpio_1_0_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_axi_gpio_1_0/design_hw_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_1_0 || ORIG_REF_NAME==design_hw_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_2_2/design_hw_axi_gpio_2_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_2_2 || ORIG_REF_NAME==design_hw_axi_gpio_2_2}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_2_2/design_hw_axi_gpio_2_2_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_axi_gpio_2_2/design_hw_axi_gpio_2_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_2_2 || ORIG_REF_NAME==design_hw_axi_gpio_2_2}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_3_0/design_hw_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_3_0 || ORIG_REF_NAME==design_hw_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_axi_gpio_3_0/design_hw_axi_gpio_3_0_ooc.xdc

# XDC: bd/design_hw/ip/design_hw_axi_gpio_3_0/design_hw_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_hw_axi_gpio_3_0 || ORIG_REF_NAME==design_hw_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/design_hw/ip/design_hw_auto_pc_0/design_hw_auto_pc_0_ooc.xdc

# XDC: bd/design_hw/design_hw_ooc.xdc
