webtalk_init -webtalk_dir F:\\Proiecte_si_concursuri\\WWS\\WWS\\ZYBO\\zybo_vivado_proj\\zybo_vivado_proj.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Ma Mai 3 21:54:51 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "mpdu9oise3u127ce7sgjoau13p" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_19" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1462102428627" -context "sdk\\\\bsp/1462102428627"
webtalk_add_data -client sdk -key hwid -value "1455921393984" -context "sdk\\\\bsp/1462102428627"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1462102428627"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1462102428627"
webtalk_add_data -client sdk -key uid -value "1462301041950" -context "sdk\\\\bsp/1462301041950"
webtalk_add_data -client sdk -key hwid -value "1455921393984" -context "sdk\\\\bsp/1462301041950"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1462301041950"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1462301041950"
webtalk_add_data -client sdk -key uid -value "1462301071372" -context "sdk\\\\application/1462301071372"
webtalk_add_data -client sdk -key hwid -value "1455921393984" -context "sdk\\\\application/1462301071372"
webtalk_add_data -client sdk -key bspid -value "1462301041950" -context "sdk\\\\application/1462301071372"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1462301071372"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1462301071372"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1462301071372"
webtalk_transmit -clientid 2486562574 -regid "" -xml F:\\Proiecte_si_concursuri\\WWS\\WWS\\ZYBO\\zybo_vivado_proj\\zybo_vivado_proj.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\Proiecte_si_concursuri\\WWS\\WWS\\ZYBO\\zybo_vivado_proj\\zybo_vivado_proj.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\Proiecte_si_concursuri\\WWS\\WWS\\ZYBO\\zybo_vivado_proj\\zybo_vivado_proj.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
